### ISSUE TITLE
Check repo url starts with http/s

### ISSUE THREAD

**Issue by andrewromanenco** [andrewromanenco/git.android#3]
At this point app supports only http and https repos. Make friendly alert when this is not a case

**Comment by carltonwhitehead** [comment]
Perhaps this belongs as a new issue, but it seems the underlying jgit library should have support for other protocols besides http(s). Is there much additional complexity implementing those? Perhaps jgit has a call to get supported protocols which could be used for this validation check.

**Comment by andrewromanenco** [comment]
Hi

jgit supports all operations and protocols. Including key based authentication.
I will add ssh support at some time - right now there are few more useful changes in the queue.

will open separate ticket for this one
